
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Lexer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else = 24;
  public static final int LeftEqual = 14;
  public static final int Plus = 7;
  public static final int Then = 18;
  public static final int Mul = 5;
  public static final int UNRECOGNIZEDCHAR = 26;
  public static final int Right = 12;
  public static final int Var = 22;
  public static final int Assign = 9;
  public static final int Difference = 10;
  public static final int RightEqual = 11;
  public static final int Minus = 6;
  public static final int Left = 13;
  public static final int EndWhile = 20;
  public static final int EOF = 0;
  public static final int Num = 2;
  public static final int If = 23;
  public static final int NegNum = 3;
  public static final int error = 1;
  public static final int SemiColon = 15;
  public static final int Do = 21;
  public static final int Equal = 8;
  public static final int Div = 4;
  public static final int While = 25;
  public static final int EndIf = 19;
  public static final int LeftParenthesis = 16;
  public static final int RightParenthesis = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Num",
  "NegNum",
  "Div",
  "Mul",
  "Minus",
  "Plus",
  "Equal",
  "Assign",
  "Difference",
  "RightEqual",
  "Right",
  "Left",
  "LeftEqual",
  "SemiColon",
  "LeftParenthesis",
  "RightParenthesis",
  "Then",
  "EndIf",
  "EndWhile",
  "Do",
  "Var",
  "If",
  "Else",
  "While",
  "UNRECOGNIZEDCHAR"
  };
}

